library(plyr)
library(ggplot2)


#Answer 1
activity <- read.csv("activity.csv") 
activity$date <- as.POSIXct(activity$date)

dailysteps <- aggregate(activity$steps, by = list(activity$date), sum, na.rm=TRUE) 
names(dailysteps) <- c("Date", "steps")

#Answer 2
#hist plot
qplot(steps, data = dailysteps, geom="histogram", xlab = "Daily Number of Steps", binwidth = 300)

#Answer 3
mean.steps <- mean(dailysteps$steps) 
median.steps <- median(dailysteps$steps)

#Answer 4
#calculate average number of steps by intervals without missing values
avg_no_stps_intvl <- as.data.frame(tapply(activity$steps, 
                                          INDEX = activity$interval, 
                                          FUN = "mean", na.rm = TRUE))
#Name the calculated average column to avg_steps
colnames(avg_no_stps_intvl) <- "avg_steps"
#Name rownames to interval as INDEX has created unterval as rownames
avg_no_stps_intvl$interval <- rownames(avg_no_stps_intvl)
row.names(avg_no_stps_intvl)<-NULL
plot(avg_no_stps_intvl$interval, avg_no_stps_intvl$avg_steps, type = "l", 
     xlab = "Time Interval (5-mins)", ylab = "Average number of steps", 
     main = "Average Number of Steps by Time  Interval", col="blue")

#Answer 5
most.steps <- avg_no_stps_intvl$interval[avg_no_stps_intvl$avg_steps == max(avg_no_stps_intvl$avg_steps)]
most.steps

#Answer 6
na.steps <- subset(activity, is.na(steps))
num.NAs <-length(na.steps$steps)
num.NAs 

#Anser 7
median_stps_intvl <- as.data.frame(tapply(activity$steps, 
                                          INDEX = activity$interval, 
                                          FUN = "median", na.rm = TRUE))
#Name calculated median column to median_steps
colnames(median_stps_intvl) <- "median_steps"
#Name rownames to interval as INDEX has created unterval as rownames
median_stps_intvl$interval <- rownames(median_stps_intvl)
row.names(median_stps_intvl)<-NULL
mean_median<-merge(median_stps_intvl,avg_no_stps_intvl, by="interval")
#merge mean and median with original data with missing
acmDT_with_summ<-merge(activity,mean_median, by="interval")


#sum the number of steps each day into the dailysteps2 DF and get the mean and median 
dailysteps2 <- aggregate(activity$steps, by = list(activity$date), sum, na.rm=TRUE)
names(dailysteps2) <- c("Date", "steps")

qplot(steps, data = dailysteps2, geom="histogram", xlab = "Daily Number of Steps", binwidth = 300)

# Add the Weekday/weekend identifier

activity$week <- ifelse(weekdays(activity$date) == "Saturday" | weekdays(activity$date) == "Sunday" ,"weekend","weekday")

#df of the mean and median number of steps taken, averaged across all days (y-axis)
intsteps2 <- aggregate(activity$steps, by = list(activity$week, activity$interval), mean, na.rm=TRUE)
intstepsmed2 <- aggregate(activity$steps, by = list(activity$week, activity$interval), median, na.rm=TRUE)

intsteps2 <- cbind(intsteps2[], intstepsmed2$x)

#Tidy the df names and round the numbers
names(intsteps2) = c("weekday", "interval","mean.steps", "median.steps")
intsteps2$mean.steps <- round(intsteps2$mean.steps)
intsteps2$median.steps <- round(intsteps2$median.steps)

ggplot(intsteps2, aes(x = interval, y = mean.steps)) + ylab("Number of Steps") + geom_line() + facet_grid(weekday~.)